### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by systeembeheerder**
Installation also works for the current Debian stable (12/bookworm) with a small edit.

### CODE REVIEW

**Comment by systeembeheerder** [comment]
unfortunately support for php 8.2 is far from complete on this project.

**Comment by mbolli** [comment]
@systeembeheerder there's an open branch for PHP 8.2 if you want to test it https://github.com/mbolli/nfsen-ng/pull/90

**Comment by systeembeheerder** [comment]
I tried and gave up really quick.

**First**
The installation instructions did not mention the dependency on php-mbstring
**Second**
```
# ./cli.php
PHP Warning:  include_once(/opt/nfsen-ng/backend/common/debug.php): Failed to open stream: No such file or directory in /opt/nfsen-ng/backend/cli.php on line 5
```
Should include Debug.php, debug.php does not exists.
**Third**
After creating a symlink named debug.php pointing to Debug.php
```
PHP Fatal error:  Uncaught Error: Typed static property nfsen_ng\common\Debug::$_instance must not be accessed before initialization in /opt/nfsen-ng/backend/common/Debug.php:17
Stack trace:
#0 /opt/nfsen-ng/backend/cli.php(12): nfsen_ng\common\Debug::getInstance()
#1 {main}
  thrown in /opt/nfsen-ng/backend/common/Debug.php on line 17
```

I have no idea how to fix this.

**Comment by mbolli** [comment]
Thanks for the details, can you try again after a pull?

**Pull request closed without merging**
